# Generated by Django 3.0.2 on 2020-02-07 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectslist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projectslist', to=settings.AUTH_USER_MODEL),
        ),
    ]
