# Generated by Django 3.0.2 on 2020-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0008_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('karachi', 'Karachi'), ('faisalabad', 'Faisalabad'), ('lahore', 'Lahore'), ('islamabad', 'Islamabad'), ('quetta', 'Quetta')], default='green', max_length=12),
        ),
    ]
